spring:
  application:
    name: pedido-hexagonal
  server:
    port: 8083

  datasource:
    url: jdbc:postgresql://localhost:5432/pedidos-db
    username: postgres
    password: gabriel18
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092  # Kafka rodando no Docker, acessível pela máquina local
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: pedido-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false

topicos:
  pedidos:
    request:
      topic: pedidos-request
